Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Max: 30

AllCops:
  Exclude:
    - 'config/initializers/devise.rb'
    - 'config/environments/development.rb'
    - 'bin/**/*'
    - 'config/initializers/secret_token.rb'
    - 'db/schema.rb'
    - 'db/migrate/*'

