defaults: &defaults
  smtp_settings:
    address: 'smtp.gmail.com'
    domain: 'gmail.com'
    user_name: 'eventplus.mailer@gmail.com'
    password: 'Ahha546372819!'

  db:
    username: eventplus
    password: Ahha546372819!
    url: postgres://eventplus:Ahha546372819!@localhost:5432/eventplus


development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults